#! /bin/sh
### BEGIN INIT INFO
# Provides: motiondetection
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: motion detection
# Description:
### END INIT INFO
 
case "$1" in
    start)
        echo "mario wird gesucht"
        # Starte Programm
        nohup /usr/bin/luigi > /var/log/motion.log &
        ;;
    stop)
        echo "suche nach mario wird beendet"
        # Beende Programm
	#PID=$(ps aux | grep pir.py | grep -v grep | grep -v sudo | awk '{print $2}')
	#kill $PID
	touch /tmp/stop_motiondetection
        ;;
    *)
        echo "Benutzt: /etc/init.d/motiondetection {start|stop}"
        exit 1
        ;;
esac
 
exit 0
